### ISSUE TITLE
Missing Install Instructions

### ISSUE THREAD

**Issue by ffledgling** [schickele/vim-nachtleben#1]
I found this theme via vimcolors.net, it looks great in the screenshots, unfortunately I haven't been able to get it working at all. I'm using pathogen, and have it installed via the usual method of cloning this repo as a submodule under `~/.vim/bundle/`. The theme is recognized and I can change to it manually. However, it doesn't actually do anything in any files (Python, vimrc, LaTeX) for me. Do I need to add other directives to get it working? Do I need to configure my terminal specifically? How does it work?

**Comment by schickele** [comment]
I do not use Pathogen for color schemes, but I've added some install notes. Hope this helps.

**Comment by ffledgling** [comment]
@schickele Yep, works for me now even with Pathogen. Thanks!

**Comment by schickele** [comment]
You're welcome!
